package assessment.factories.user;

/**
 * Created by hmccardell on 3/29/2016.
 */
public enum UserOption {

    VALID_ACTIVE_DEVELOPER,
    VALID_INACTIVE_DEVELOPER,
    INVALID_USER_FIRST_NAME_EMPTY,
    INVALID_USER_FIRST_NAME_NULL,
    INVALID_USER_FIRST_NAME_SPECIAL_CHARACTERS,
    INVALID_USER_FIRST_NAME_LONG,
    INVALID_USER_LAST_NAME_EMPTY,
    INVALID_USER_LAST_NAME_NULL,
    INVALID_USER_LAST_NAME_SPECIAL_CHARACTERS,
    INVALID_USER_LAST_NAME_LONG,
    INVALID_USER_EMAIL_EMPTY,
    INVALID_USER_EMAIL_NULL,
    INVALID_USER_EMAIL_INVALID_ADDRESS,
    INVALID_USER_VERSION_ZERO,
    INVALID_USER_VERSION_NULL,
    INVALID_USER_DESCRIPTION_LONG,
    INVALID_USER_ISACTIVE_NULL,
    INVALID_USER_TITLE_NULL,
    INVALID_USER_TITLE_EMPTY
}
