package assessment.factories.period;

public enum PeriodOption {

    VALID_PERIOD_WITH_ID,
    VALID_PERIOD_WITHOUT_ID,
    INVALID_PERIOD_TEMPLATEID_NULL,
    INVALID_PERIOD_TEMPLATEID_EMPTY,
    INVALID_PERIOD_SERIES_NUMBER_NULL,
    INVALID_PERIOD_SERIES_NUMBER_ZERO,
    INVALID_PERIOD_NAME_NULL,
    INVALID_PERIOD_NAME_WITH_SPECIAL_CHARS,
    INVALID_PERIOD_NAME_EMPTY_STRING,
    INVALID_PERIOD_NAME_TOO_LONG,
    INVALID_PERIOD_TEAM_ID_NULL,
    INVALID_PERIOD_TEAM_ID_EMPTY_STRING,
    INVALID_PERIOD_DATE_NULL,
    INVALID_PERIOD_SUMMARY_SCORE_MIN,
    INVALID_PERIOD_SUMMARY_SCORE_MAX,
    INVALID_PERIOD_VERSION_NULL,
    INVALID_PERIOD_VERSION_ZERO,

}
