package assessment.factories.assessment;

/**
 * Created by jtucker on 4/5/2016.
 */
public enum AssessmentOption {

    VALID_ASSESSMENT,
    INVALID_ASSESSMENT_NAME_LONG,
    INVALID_ASSESSMENT_NAME_SPECIAL_CHARACTERS,
    INVALID_ASSESSMENT_NULL_NAME,
    INVALID_ASSESSMENT_VERSION_ZERO,
    INVALID_ASSESSMENT_VERSION_NULL
}
