package assessment.factories.kudo;

/**
 * Created by hmccardell on 4/27/2016.
 */
public enum KudoOption {

    VALID_KUDO,
    INVALID_KUDO_REVIEWED_NULL,
    INVALID_KUDO_REVIEWER_NULL,
    INVALID_KUDO_SELF_REVIEW,
    INVALID_KUDO_COMMENT_LONG,
    INVALID_KUDO_DATE_NULL,
    INVALID_KUDO_DATE_PAST,
    INVALID_KUDO_VERSION_NULL,
    INVALID_KUDO_VERSION_0

}
