package assessment.factories.membership;

/**
 * Created by hmccardell on 4/1/2016.
 */
public enum MembershipOption {

    VALID_ACTIVE_MEMBERSHIP,
    INVALID_MEMBERSHIP_ID_EMPTY,
    INVALID_MEMBERSHIP_ISACTIVE_NULL,
    INVALID_MEMBERSHIP_ADDED_DATE_NULL,
    INVALID_MEMBERSHIP_VERSION_ZERO,
    INVALID_MEMBERSHIP_VERSION_NULL

}
