package assessment.factories.team;

/**
 * Created by mmosley on 4/29/2016.
 */
public enum ReviewPeriodOption {

    VALID_REVIEW_PERIOD,
    INVALID_REVIEW_PERIOD_NAME_EMPTY,
    INVALID_REVIEW_PERIOD_NAME_SPECIAL_CHARACTERS,
    INVALID_REVIEW_PERIOD_NAME_TOO_LONG,
    INVALID_REVIEW_PERIOD_FREQUENCY_NULL,
    INVALID_REVIEW_PERIOD_TEMPLATE_ID_EMPTY,
    INVALID_REVIEW_PERIOD_CURRENT_PERIOD_ID_EMPTY

}
