package assessment.factories.question;

/**
 * Created by jtucker on 3/31/2016.
 */
public enum QuestionOption {

    VALID_BOOLEAN_QUESTION, VALID_MULTIPLE_CHOICE_QUESTION, VALID_COMPETENCY_QUESTION,
    NULL_TYPE_QUESTION, LONG_LABEL_QUESTION, EMPTY_LABEL_QUESTION,
    NULL_LABEL_QUESTION, NULL_VERSION_QUESTION

}
