package assessment.factories.review;

/**
 * Created by jtucker on 4/1/2016.
 */
public enum ReviewOption {

    VALID_REVIEW, NULL_REVIEWER_ID_REVIEW, NULL_REVIEWED_ID_REVIEW,
    EMPTY_TEAM_NAME_REVIEW, NULL_TEAM_NAME_REVIEW, NULL_SUBMITTED_DATE_REVIEW,
    EMPTY_FEEDBACK_REVIEW, NULL_FEEDBACK_REVIEW, NULL_VERSION_REVIEW

}
