package assessment.factories.review;

/**
 * Created by jtucker on 4/1/2016.
 */
public enum ReviewOption {

    VALID_REVIEW,
    INVALID_REVIEW_REVIEWER_ID_NULL,
    INVALID_REVIEW_REVIEWER_ID_EMPTY,
    INVALID_REVIEW_REVIEWED_ID_NULL,
    INVALID_REVIEW_REVIEWED_ID_EMPTY,
    INVALID_REVIEW_SUBMITTED_DATE_NULL,
    INVALID_REVIEW_FEEDBACK_EMPTY,
    INVALID_REVIEW_FEEDBACK_NULL,
    INVALID_REVIEW_VERSION_NULL,
    INVALID_REVIEW_VERSION_ZERO,
    INVALID_REVIEW_SUMMARY_SCORE_SMALL,
    INVALID_REVIEW_SUMMARY_SCORE_LARGE,
	INVALID_TEAM_NAME_SPECIAL_CHARACTERS,
	INVALID_TEAM_NAME_TOO_LONG,
	INVALID_TEAM_NAME_NULL,
    INVALID_REVIEW_SELF_REVIEW

}
