package assessment.factories.feedback;

/**
 * Options for the feedback entity you want
 */
public enum FeedbackOption {
    VALID_FEEDBACK,
    INVALID_FEEDBACK_LABEL_EMPTY,
    INVALID_FEEDBACK_LABEL_TOO_LONG,
    INVALID_FEEDBACK_SCORE_ZERO,
    INVALID_FEEDBACK_SCORE_OVERBOUND,
    INVALID_FEEDBACK_COMMENT_TOO_LONG,
    INVALID_FEEDBACK_VERSION_NULL,
    INVALID_FEEDBACK_VERSION_ZERO
}
