package assessment.factories.team;

/**
 * Created by Alysha Recore on 3/31/2016.
 */
public enum TeamOption {

    VALID_ACTIVE_TEAM,
    VALID_INACTIVE_TEAM,
    INVALID_TEAM_DUPLICATE,
    INVALID_TEAM_NAME_SPECIAL_CHARACTERS,
    INVALID_TEAM_NAME_TOO_LONG,
    INVALID_TEAM_NAME_NULL,
    INVALID_TEAM_IS_ACTIVE_NULL,
    INVALID_TEAM_DESCRIPTION_TOO_LONG,
    INVALID_TEAM_VERSION_NULL,
    INVALID_TEAM_VERSION_ZERO
}
