package assessment.factories.team;

/**
 * Created by Alysha Recore on 3/31/2016.
 */
public enum TeamOption {

    VALID_ACTIVE_TEAM,
    VALID_INACTIVE_TEAM,
    INVALID_TEAM_NAME_SPECIAL_CHARACTERS,
    INVALID_TEAM_NAME_LONG,
    INVALID_TEAM_NAME_NULL,
    INVALID_TEAM_ACTIVE_NULL,
    INVALID_TEAM_TYPE_NULL,
    INVALID_TEAM_VERSION_NULL,
    INVALID_TEAM_VERSION_ZERO
}
