package assessment.factories.question;

/**
 * Created by jtucker on 3/31/2016.
 */
public enum QuestionOption {

    VALID_BOOLEAN_QUESTION,
    VALID_MULTIPLE_CHOICE_QUESTION,
    VALID_COMPETENCY_QUESTION,
    INVALID_QUESTION_TYPE_NULL,
    INVALID_QUESTION_LABEL_LONG,
    INVALID_QUESTION_LABEL_EMPTY,
    INVALID_QUESTION_LABEL_NULL,
    INVALID_QUESTION_VERSION_NULL,
    INVALID_QUESTION_VERSION_ZERO

}
